# logging: true
env_name: SlayTheSpire
log_path: "logs"
env:
  task: "Slay the Spire"
  player_class: "IRONCLAD"
  ascension_level: 0
  seed: 0
  input_modality: "text"
  mod_input_path: "YOUR_ABSOLUTE_PATH\\data\\slay_the_spire\\mod_input.txt"
  mod_output_path: "YOUR_ABSOLUTE_PATH\\data\\slay_the_spire\\mod_output.txt"
