# logging: true
env_name: "BabaIsYou"
log_path: "logs"
runner:
  max_steps: 30
env:
  task: "where do i go?" # Name of Level 1
  state_json_path: "%APPDATA%/Baba_Is_You/state.ba" # "~/Library/Application Support/Baba_Is_You/state.ba" fo MacOS
  input_modality: "text_image"

# Agent configuration
agent:
  llm_name: gpt-4o
  api_key: "token-abc123"
  api_base_url: "http://YOUR_LOCAL_IP:PORT/v1"
  temperature: 0.7
  repetition_penalty: 1.0
  agent_type: reflection_planning_agent
  prompt_path: mcp_agent_servers.baba_is_you.prompts.text_image.reflection_planning_agent

# mcp configuration
game_server: "./src/mcp_game_servers/baba_is_you/server.py"
agent_server: "./src/mcp_agent_servers/baba_is_you/server.py"