# logging: true
env_name: "PokemonRed"
log_path: ./logs
runner:
  max_steps: 1000
env:
  task: DefeatBrock
  input_modality: "text"
  exp_name: "gpt-4o_text_pokemon_trial1"
  rom_path: ./executables/pokemon_red/pyboy/pokered.gbc
  success_condition: get_boulder_badge

# Agent configuration
agent: 
  debug_mode: false
  llm_name: gpt-4o-mini
  api_key: "token-abc123"
  api_base_url: "http://YOUR_LOCAL_IP:PORT/v1"
  temperature: 0.1
  repetition_penalty: 1.0
  agent_type: pokemon_agent
  prompt_path: mcp_agent_servers.pokemon_red.prompts.text.pokemon_agent

# # mcp configuration
# game_server: ".\\src\\mcp_game_servers\\pokemon_red\\server.py"
# agent_server: ".\\src\\mcp_agent_servers\\pokemon_red\\server.py"