# flake8: noqa

PROMPT = (
    f"Current subtask:\n"
    f"{{subtask_description}}\n\n"
    f"Last executed action for completing the subtask:\n"
    f"{{action}}\n\n"
    f"Previous state:\n"
    f"{{prev_state_str}}\n\n"
    f"Current state:\n"
    f"{{cur_state_str}}\n\n"
    f"Reasoning: You need to answer the following questions step by step to get reasoning based on the last action and the states.\n"
    f"1. What is the executed action and its desired result?\n"
    f"2. What is the difference between two states? Compare every component in each state.\n"
    f"3. Were the movements made got blocked by any obstacles? If so, identify where it got blocked.\n"
    f"4. Has the current subtask been accomplished?\n"
    f"5. Do you need to change the current subtask? Give reasons.\n"
    f"You should only respond in the format as described below.\n"
    f"### Reasoning\n"
    f"1. ...\n"
    f"2. ...\n"
    f"3. ...\n"
    f"4. ...\n"
    f"5. ...\n"
    f"### Self_reflection\n"
    f"[A summary of the above reasoning]"
)