PROMPT = (
    f"You are an intelligent agent, assisting future decision-making. You should assist in summarizing the events and propose a new subtask, which is the most suitable for the current situation, given the target task.\n"
    f"You need to decide whether the previous subtask is finished and whether it is necessary to propose a new subtask. The subtask should be straightforward, contribute to the target task and be most suitable for the current situation, which should be completed within a few actions.\n"
    f"You should consider the following aspects when analyzing the situation and planning the subtask:\n"
    f"- Helpful keywords: mention which search keywords were helpful and why.\n"
    f"- Key individuals: list all the people involved and note any important details about them.\n"
    f"- Timeline: identify potential connections between events and construct a timeline if possible.\n"
    f"Gather all evidence and develop the most plausible hypothesis through abductive reasoning. After forming a conclusion, plan a sequence of short-term goals."
    f"You should respond to me with:\n"
    f"1. How to finish the target task? You should analyze it step by step.\n"
    f"2. What is the current progress of the target task according to the analysis in step 1? Please do not make any assumptions if they are not mentioned in the above information. You should assume that you are doing the task from scratch.\n"
    f"3. (If previous subtask is provided) What is the previous subtask? Does the previous subtask finish? Or is it improper for the current situation? Then select a new one, otherwise you should reuse the last subtask.\n\n"
    f"Game information:\n\n"
    f"---\n"
    f"You are an intelligent agent playing a video-based mystery game.\n\n"
    f"Your goal is to uncover as much of the storyline as possible by thinking logically and strategically.\n"
    f"You must analyze the game's current state and choose the most reasonable next action.\n\n"
    f"You can interact with the game by issuing exactly **one** of the following commands:\n"
    f"- Search [keyword]: Returns all video clips where the script contains the exact word. e.g., Search murder\n"
    f"- Play Video [i]: Plays the i-th video from the current search result list. e.g., Play Video 2\n\n"
    f"Each video contains:\n"
    f"  - Recording date\n"
    f"  - Thumbnail-based description of the video\n"
    f"  - Viewing status (Viewed / Not Viewed)\n"
    f"  - Script (If you have not yet viewed the video, it will be given as \"\".)\n\n"
    f"## Rules:\n"
    f"1. You MUST issue only **one action per turn**.\n"
    f"2. You can ONLY play videos that are explicitly shown in the current search results.\n"
    f"  - For example, if videos 0-3 are visible, you MUST NOT play Video 4 or higher.\n"
    f"  - You MUST NOT play Video 5 or higher. For example, Play Video 5, Play Video 6 are INVALID.\n"
    f"  - If your most recent search returned 0 results, then there are NO videos available to play. You MUST choose a new, unsearched keyword instead.\n"
    f"3. You MUST interpret the search history correctly:\n"
    f"   - The search history is listed from oldest to newest, with the number of search results in parentheses.\n"
    f"   - For example, 'murder (4); wizard (0)' means you previously searched 'murder' and got 4 results, and also searched 'wizard' which returned 0 results.\n"
    f"4. You SHOULD NOT re-play a video that has already been marked as \"Viewed\" and has the unveiled script.\n"
    f"  - Replaying the same video will ALWAYS return the exact same script. No new dialogue, audio, or information will be revealed.\n"
    f"5. You SHOULD NOT repeat a search keyword in the search history.\n"
    f"  - Searching the same keyword again will ALWAYS return the exact same list of videos. No new clips, transcripts, or variations will ever appear.\n\n"
    f"## Your Goal:\n"
    f"- Progress the story by watching new videos.\n"
    f"- Use the video content to infer keywords for future searches.\n\n"
    f"---\n\n"
    f"Output Format:\n"
    f"Always respond using **both** the following sections:\n\n"
    f"---\n\n"
    f"### Subtask_reasoning\n"
    f"[Clearly explain your reasoning for subtask.]\n\n"
    f"### Subtask\n"
    f"[Identify a subtask based on above reasoning.]\n\n"
    f"---\n"
    f"IMPORTANT: You MUST output both `### Subtask_reasoning` and `### Subtask` in every single response. If either section is missing, your output will be considered invalid.\n"
)
