# general configuration
# logging: true

# environment configuration
env_name: StarCraftMulti
log_path: ./logs
runner:
  max_steps: 10000
env:
  task: 1 vs 1 battle between agents
  input_modality: "text" # text, image, text_image
  map_idx: 1
  player1_race: Protoss
  player2_race: Protoss
  query_interval: 10
  num_summaries: 1
  num_actions: 5

# agent configuration
agent1:
  llm_name: gpt-4o-mini
  # llm_name: o3-mini
  # llm_name: gemini-2.5-pro-preview-03-25
  # llm_name: Qwen/Qwen2.5-7B-Instruct
  # llm_name: meta-llama/Llama-3.2-3B-Instruct
  # llm_name: nvidia/Mistral-NeMo-Minitron-8B-Instruct
  api_key: "token-abc123"
  # api_base_url: "YOUR_LOCAL_IP:PORT/v1"
  # api_base_url: "YOUR_LOCAL_IP:PORT/v1"
  api_base_url: "http://YOUR_LOCAL_IP:PORT/v1"
  temperature: 0.1
  repetition_penalty: 1.0
  debug_mode: false
  agent_type: reflection_planning_agent
  prompt_path: mcp_agent_servers.star_craft.prompts.text.reflection_planning_agent

agent2:
  llm_name: gpt-4o
  # llm_name: gemini-2.5-pro-preview-03-25
  # llm_name: meta-llama/Llama-3.2-3B-Instruct
  # llm_name: Qwen/Qwen2.5-7B-Instruct
  # llm_name: nvidia/Mistral-NeMo-Minitron-8B-Instruct
  # llm_name: claude-3-7-sonnet-20250219
  api_key: "token-abc123"
  api_base_url: "http://YOUR_LOCAL_IP:PORT/v1"
  # api_base_url: "http://YOUR_LOCAL_IP:PORT/v1"
  temperature: 0.1
  repetition_penalty: 1.0
  debug_mode: false
  agent_type: reflection_planning_agent
  prompt_path: mcp_agent_servers.star_craft.prompts.text.reflection_planning_agent

# mcp configuration
game_server: ".\\src\\mcp_game_servers\\star_craft\\server.py"
agent_server: ".\\src\\mcp_agent_servers\\star_craft\\server.py"