# logging: true
env_name: "BabaIsYou"
log_path: ./logs
agent:
  llm_name: gpt-4o-mini
  # structured_output:
  #   action_inference:
  #     # JSON SCHEMA
  #     guided_json: ActionSchema
  #     output_keys:
  #       - action

      # REGEX
      # guided_regex: "### Reasoning\\s*\\n(.+?)\\n### Actions\\s*\\n(.+)"
      # guided_decoding_backend: "outlines"

  api_key: "token-abc123"
  api_base_url: "http://YOUR_LOCAL_IP:PORT/v1"
  temperature: 0.7
  repetition_penalty: 1.0
  agent_type: reflection_planning_agent
  prompt_path: mcp_agent_servers.baba_is_you.prompts.text.reflection_planning_agent