# logging: true
env_name: Minecraft
log_path: ./logs
env:
  task: craft 1 golden sword
  input_modality: "text" # text
  success_condition: golden_sword
  world_seed: 42
  azure_login_path: keys/azure-login/azure_login.json
  server_host: http://127.0.0.1
  server_port: 3000
  request_timeout: 600
  logging: false