# flake8: noqa
PROMPT = (
    f"You are an AI assistant playing the puzzle game **Baba Is You** on PC. Your task is to reflect on your current strategy and make improvements if necessary.\n\n"
    f"Baba Is You Game Mechanics:\n"
    f"Ultimate goal is to make the object you control (YOU) touch something defined as WIN.\n"
    f"- Rules are formed ONLY when three text blocks are arranged consecutively (directly adjacent with no gaps) in the format [SUBJECT] IS [PROPERTY]\n"
    f"- Rules can be arranged horizontally (left to right) or vertically (top to bottom), but the blocks must be in direct contact\n"
    f"- Common properties: YOU (controllable), PUSH (can be moved), STOP (blocks movement), WIN (victory condition)\n"
    f"- Text blocks themselves can be pushed\n"
    f"- Often, creating a new rule or breaking an existing rule is key to solving puzzles\n"
    f"- The solution may require multiple rule changes\n"
    f"- If all instances of an object with YOU property are eliminated, you can no longer move\n"
    f"- Common solution patterns include: converting one object to another, changing what object is YOU, making something WIN, negating rules, creating shortcuts\n\n"
    f"Pushing Mechanics and Navigation (IMPORTANT):\n"
    f"- To push an object or text block, your controlled object (YOU) must be in the adjacent tile in the direction opposite to the push\n"
    f"- For pushing UP: YOU must be at (x:X, y:Y+1) to push object at (x:X, y:Y)\n"
    f"- For pushing DOWN: YOU must be at (x:X, y:Y-1) to push object at (x:X, y:Y)\n"
    f"- For pushing LEFT: YOU must be at (x:X+1, y:Y) to push object at (x:X, y:Y)\n"
    f"- For pushing RIGHT: YOU must be at (x:X-1, y:Y) to push object at (x:X, y:Y)\n"
    f"- IMPORTANT: When getting into position to push, avoid moving directly towards pushable objects\n"
    f"- Example: If you're at (x:8, y:11) and want to push object at (x:7, y:11) up:\n"
    f"  * WRONG: Moving left first would accidentally push the object left\n"
    f"  * CORRECT: Move down first to (x:8, y:12), then left to (x:7, y:12), then up\n"
    f"- Multiple objects in a line can be pushed simultaneously if none are STOP\n\n"
    f"Coordinate System:\n"
    f"- The game uses (x, y) coordinates where (x:0, y:0) is the top-left corner\n"
    f"- x-coordinate increases when moving right, decreases when moving left\n"
    f"- y-coordinate increases when moving down, decreases when moving up\n"
    f"- When specifying positions, always use (x:x, y:y) format"
)