# logging: true
env_name: Pwaat
log_path: ./logs
agent:
  # llm_name: nvidia/Mistral-NeMo-Minitron-8B-Instruct
  debug_mode: true
  llm_name: gpt-4o-mini #o3-mini, gpt-4o, gpt-4o-mini
  api_key: "token-abc123"
  api_base_url: "http://YOUR_LOCAL_IP:PORT/v1"
  temperature: 0.7
  repetition_penalty: 1.0
  agent_type: reflection_agent
  prompt_path: mcp_agent_servers.pwaat.prompts.text_image.reflection_agent
  long_term_memory_len: 5
