# logging: true
env_name: Minecraft
log_path: ./logs
agent:
  llm_name: gpt-4o-mini # Qwen/Qwen2.5-7B-Instruct
  api_key: "token-abc123"
  api_base_url: "http://YOUR_LOCAL_IP:PORT/v1"
  temperature: 1.0
  repetition_penalty: 1.0
  agent_type: skill_management_agent
  prompt_path: mcp_agent_servers.minecraft.prompts.text.skill_management_agent
